functions:
  cognitoSignUp:
    handler: src/lambdas/cognito/signUp.handler
    events:
      - httpApi:
          path: /auth/sign-up
          method: POST
  cognitoAccountConfirmation:
    handler: src/lambdas/cognito/accountConfirmation.handler
    events:
      - httpApi:
          path: /auth/account-confirmation
          method: POST
  cognitoSignIn:
    handler: src/lambdas/cognito/signIn.handler
    events:
      - httpApi:
          path: /auth/sign-in
          method: POST
  cognitoRefreshToken:
    handler: src/lambdas/cognito/refreshToken.handler
    events:
      - httpApi:
          path: /auth/refresh-token
          method: POST
  cognitoForgotPassword:
    handler: src/lambdas/cognito/forgotPassword.handler
    events:
      - httpApi:
          path: /auth/forgot-password
          method: POST
  cognitoResetPassword:
    handler: src/lambdas/cognito/resetPassword.handler
    events:
      - httpApi:
          path: /auth/reset-password
          method: POST
  cognitoUserProfile:
    handler: src/lambdas/cognito/userProfile.handler
    events:
      - httpApi:
          path: /user-profile
          method: GET
          authorizer:
            name: CognitoAuthorizer
  cognitoCustomMessage:
    handler: src/lambdas/cognito/customMessage.handler
    events:
      - cognitoUserPool:
          pool: UserPool
          trigger: CustomMessage
          existing: true
          forceDeploy: true

resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: UserPool
      DeletionProtection: INACTIVE
      MfaConfiguration: OFF
      AutoVerifiedAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      UsernameAttributes:
        - email
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: admin_only
            Priority: 1
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: true
          RequireUppercase: false
          TemporaryPasswordValidityDays: 2
      Schema:
        - Name: given_name
          Mutable: true
          Required: true
          AttributeDataType: String
        - Name: family_name
          Mutable: true
          Required: true
          AttributeDataType: String
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: UserPoolClient
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      TokenValidityUnits:
        AccessToken: hours
        RefreshToken: hours
      AccessTokenValidity: 3
      RefreshTokenValidity: 720 # 30 days
