service: serveless-node-infra
frameworkVersion: '4'

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-iam-roles-per-function

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node22
    platform: node
    exclude:
      - '@aws-sdk/*'

custom:
  serverless-offline:
    useChildProcesses: true
  serverless-dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      shareDB: true
      migrate: true
      convertEmptyValues: true
      noStart: true
  environment:
    # # Cognito # #
    # COGNITO_CLIENT_ID: !Ref UserPoolClient
    # COGNITO_POOL_ID: !Ref UserPool
    # # DynamoDB # #
    # PRODUCTS_TABLE: !Ref ProductsTable
    # # S3 # #
    # UPLOAD_FILE_TABLE: !Ref UploadedFilesTable
    # FILE_UPLOAD_BUCKET: !Ref FileUploaderBucket

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  # profile: app
  timeout: 10 # optional, in seconds, default is 6
  region: us-east-1
  httpApi:
    cors: true
    # # Cognito # #
    # authorizers:
    #   CognitoAuthorizer:
    #     type: jwt
    #     identitySource: $request.header.Authorization
    #     issuerUrl: !GetAtt UserPool.ProviderURL
    #     audience:
    #       - !Ref UserPoolClient

  environment:
    DEBUG: ${env:DEBUG, false}
    STAGE: ${self:provider.stage}

functions:
  # - ${file(src/resources/cognito/serverless.yml):functions}
  # - ${file(src/resources/dynamoDB/serverless.yml):functions}
  # - ${file(src/resources/s3/serverless.yml):functions}
  # - ${file(src/resources/sqs/serverless.yml):functions}

resources:
  # - ${file(src/resources/cognito/serverless.yml):resources}
  # - ${file(src/resources/dynamoDB/serverless.yml):resources}
  # - ${file(src/resources/s3/serverless.yml):resources}
  # - ${file(src/resources/sqs/serverless.yml):resources}
  - Resources:
      CloudWatchPolicy:
        Type: AWS::IAM::Policy
        Properties:
          PolicyName: LambdaCloudWatchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:TagResource
                Resource:
                  - 'Fn::Join':
                      - ':'
                      - - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
          Roles:
            # - Ref: S3UploadRole
            # - Ref: DynamoDBRole
            # - Ref: CognitoRole
