service: serveless-node-infra
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dynamodb
  - serverless-offline

custom:
  esbuild:
    target: node20
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'
    # define:
    #   require.resolve: undefined
    platform: node
    # concurrency: 10
  serverless-dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      shareDB: true
      migrate: true
      convertEmptyValues: true
      noStart: true
  environment:
    BUCKET_UPLOAD_NAME: !Ref FileUploaderBucket
    COGNITO_CLIENT_ID: !Ref UserPoolClient
    COGNITO_POOL_ID: !Ref UserPool

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  # profile: app
  timeout: 10 # optional, in seconds, default is 6
  region: us-east-1
  httpApi:
    cors: true
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt UserPool.ProviderURL
        audience:
          - !Ref UserPoolClient
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt ProductsTable.Arn
        - Effect: Allow
          Action:
            - cognito-idp:AdminGetUser
          Resource: !GetAtt UserPool.Arn
  environment:
    STAGE: ${self:provider.stage}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, self:custom.environment.COGNITO_CLIENT_ID}
    COGNITO_POOL_ID: ${env:COGNITO_POOL_ID, self:custom.environment.COGNITO_POOL_ID}
    BUCKET_UPLOAD_NAME: ${env:BUCKET_UPLOAD_NAME, self:custom.environment.BUCKET_UPLOAD_NAME}
    # DEBUG: ${env:DEBUG}

package:
  individually: true

functions:
  - ${file(src/resources/dynamoDB/serverless.yml):functions}
  - ${file(src/resources/cognito/serverless.yml):functions}
  - ${file(src/resources/s3/serverless.yml):functions}
resources:
  Resources: ${file(resources.yml)}
