environment:
  PRODUCTS_TABLE: !Ref ProductsTable

functions:
  dynamoDBlistProducts:
    role: DynamoDBRole
    handler: src/resources/dynamoDB/lambdas/listProducts.handler
    environment:
      PRODUCTS_TABLE: ${env:PRODUCTS_TABLE, self:custom.environment.PRODUCTS_TABLE}
    events:
      - httpApi:
          path: /dynamoDB/products
          method: GET
  dynamoDBgetProduct:
    role: DynamoDBRole
    handler: src/resources/dynamoDB/lambdas/getProduct.handler
    environment:
      PRODUCTS_TABLE: ${env:PRODUCTS_TABLE, self:custom.environment.PRODUCTS_TABLE}
    events:
      - httpApi:
          path: /dynamoDB/products/{productId}
          method: GET
  dynamoDBcreateProduct:
    role: DynamoDBRole
    handler: src/resources/dynamoDB/lambdas/createProduct.handler
    environment:
      PRODUCTS_TABLE: ${env:PRODUCTS_TABLE, self:custom.environment.PRODUCTS_TABLE}
    events:
      - httpApi:
          path: /dynamoDB/products
          method: POST
  dynamoDBupdateProduct:
    role: DynamoDBRole
    handler: src/resources/dynamoDB/lambdas/updateProduct.handler
    environment:
      PRODUCTS_TABLE: ${env:PRODUCTS_TABLE, self:custom.environment.PRODUCTS_TABLE}
    events:
      - httpApi:
          path: /dynamoDB/products/{productId}
          method: PUT
  dynamoDBdeleteProduct:
    role: DynamoDBRole
    handler: src/resources/dynamoDB/lambdas/deleteProduct.handler
    environment:
      PRODUCTS_TABLE: ${env:PRODUCTS_TABLE, self:custom.environment.PRODUCTS_TABLE}
    events:
      - httpApi:
          path: /dynamoDB/products/{productId}
          method: DELETE

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        BillingMode: PAY_PER_REQUEST
        # PointInTimeRecoverySpecification:
        # PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    DynamoDBRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: dynamoDBRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: dynamoDBPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:DeleteItem
                    - dynamodb:GetItem
                    - dynamodb:Scan
                    - dynamodb:UpdateItem
                  Resource:
                    - !GetAtt ProductsTable.Arn
