environment:
  COGNITO_CLIENT_ID: !Ref UserPoolClient
  COGNITO_POOL_ID: !Ref UserPool

functions:
  cognitoSignUp:
    role: CognitoRole
    handler: src/resources/cognito/lambdas/signUp.handler
    environment:
      COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, self:custom.environment.COGNITO_CLIENT_ID}
      COGNITO_POOL_ID: ${env:COGNITO_POOL_ID, self:custom.environment.COGNITO_POOL_ID}
    events:
      - httpApi:
          path: /auth/sign-up
          method: POST
  cognitoAccountConfirmation:
    role: CognitoRole
    handler: src/resources/cognito/lambdas/accountConfirmation.handler
    environment:
      COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, self:custom.environment.COGNITO_CLIENT_ID}
      COGNITO_POOL_ID: ${env:COGNITO_POOL_ID, self:custom.environment.COGNITO_POOL_ID}
    events:
      - httpApi:
          path: /auth/account-confirmation
          method: POST
  cognitoSignIn:
    role: CognitoRole
    handler: src/resources/cognito/lambdas/signIn.handler
    environment:
      COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, self:custom.environment.COGNITO_CLIENT_ID}
      COGNITO_POOL_ID: ${env:COGNITO_POOL_ID, self:custom.environment.COGNITO_POOL_ID}
    events:
      - httpApi:
          path: /auth/sign-in
          method: POST
  cognitoRefreshToken:
    role: CognitoRole
    handler: src/resources/cognito/lambdas/refreshToken.handler
    environment:
      COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, self:custom.environment.COGNITO_CLIENT_ID}
      COGNITO_POOL_ID: ${env:COGNITO_POOL_ID, self:custom.environment.COGNITO_POOL_ID}
    events:
      - httpApi:
          path: /auth/refresh-token
          method: POST
  cognitoForgotPassword:
    role: CognitoRole
    handler: src/resources/cognito/lambdas/forgotPassword.handler
    environment:
      COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, self:custom.environment.COGNITO_CLIENT_ID}
      COGNITO_POOL_ID: ${env:COGNITO_POOL_ID, self:custom.environment.COGNITO_POOL_ID}
    events:
      - httpApi:
          path: /auth/forgot-password
          method: POST
  cognitoResetPassword:
    role: CognitoRole
    handler: src/resources/cognito/lambdas/resetPassword.handler
    environment:
      COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, self:custom.environment.COGNITO_CLIENT_ID}
      COGNITO_POOL_ID: ${env:COGNITO_POOL_ID, self:custom.environment.COGNITO_POOL_ID}
    events:
      - httpApi:
          path: /auth/reset-password
          method: POST
  cognitoUserProfile:
    role: CognitoRole
    handler: src/resources/cognito/lambdas/userProfile.handler
    environment:
      COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, self:custom.environment.COGNITO_CLIENT_ID}
      COGNITO_POOL_ID: ${env:COGNITO_POOL_ID, self:custom.environment.COGNITO_POOL_ID}
    events:
      - httpApi:
          path: /user-profile
          method: GET
          authorizer:
            name: CognitoAuthorizer
  cognitoCustomMessage:
    role: CognitoRole
    handler: src/resources/cognito/lambdas/customMessage.handler
    environment:
      COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, self:custom.environment.COGNITO_CLIENT_ID}
      COGNITO_POOL_ID: ${env:COGNITO_POOL_ID, self:custom.environment.COGNITO_POOL_ID}
    events:
      - cognitoUserPool:
          pool: UserPool
          trigger: CustomMessage
          existing: true
          forceDeploy: true

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: UserPool
        DeletionProtection: INACTIVE
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: true
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: admin_only
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: false
            RequireSymbols: true
            RequireUppercase: false
            TemporaryPasswordValidityDays: 2
        Schema:
          - Name: given_name
            Mutable: true
            Required: true
            AttributeDataType: String
          - Name: family_name
            Mutable: true
            Required: true
            AttributeDataType: String
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref UserPool
        ClientName: UserPoolClient
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: hours
          RefreshToken: hours
        AccessTokenValidity: 3
        RefreshTokenValidity: 720 # 30 days
    CognitoRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: dynamoDBRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: dynamoDBPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - cognito-idp:AdminGetUser
                  Resource: !GetAtt UserPool.Arn
